config/routes.rb
Rails.application.routes.draw do

  root "lists#index"
  resources :lists, except: [:destroy] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :image_url

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list_bookmark, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list), status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
    # comment=params[:bookmark][:comment]
    # movie_id=params[:bookmark][:movie_id]
    # list_id=params[:list_id]
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list_bookmark
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update]

  def index
    @lists = List.all
  end

  def show
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list), status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :image_url)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [ list, bookmark ] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, collection: Movie.order(:title), prompt: "Choose a Movie" %>
  <%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/bookmarks/new.html.erb
<%= render "form", { bookmark: @bookmark, list: @list } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-light px-3">
      <a href="" class="navbar-brand me-auto">🍿🍿</a>
      <ul class="navbar-nav">
        <li class="nav-item me-3"><%= link_to "Home", lists_path %></li>
        <li class="nav-item"><%= link_to "Add New List", new_list_path %></li>
      </ul>
    </nav>

        <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.input :image_url, as: :file %>
  <%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/lists/edit.html.erb
<%= render "form", list: @list %>

app/views/lists/index.html.erb
<div style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://www.auditoria-services.com/wp-content/uploads/2016/11/The-Ultimate-1.jpg'); background-size: cover; background-position: center; height: 250px" class="d-flex justify-content-center align-items-center bg-opacity-75">
  <h1 class="text-light fs-1 fw-bold">Save All Your Movies!</h1>
</div>

<div class="container d-flex justify-content-center mt-3">
  <div class="col-10">
      <% @lists.each do |list| %>
        <div class="cards">
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.image_url %>)"><%= link_to list.name, list_path(list.id), class: "text-decoration-none text-white fs-3" %></div>
      <% end %>
    </div>
  </div>

app/views/lists/new.html.erb
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<div style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path(@list.image_url.key) %>'); background-size: cover; background-position: center; height: 250px" class="d-flex justify-content-center align-items-center bg-opacity-75">
  <h1 class="text-light fs-1 fw-bold"><%= @list.name %></h1>
</div>

<%= image_tag(@list.image_url.key) %>

<div class="container d-flex justify-content-center mt-3">
  <div class="col-10">
    <div class="d-flex justify-content-end">
      <%= link_to "edit list", edit_list_path(@list), class:"btn btn-sm btn-warning text-white rounded me-2" %>
      <%= link_to "add a movie", new_list_bookmark_path(@list), class:"btn btn-sm btn-success text-white rounded" %>
    </div>
    <div class="row g-3 mt-3">
      <% @bookmarks.each do |bookmark| %>
        <div class="col-6">
          <div class="card-trip">
            <img src="<%= bookmark.movie.poster_url %>">
            <div class="card-trip-infos">
              <div>
                <h2><%= bookmark.movie.title %><span> ∙ <%= bookmark.movie.rating %> ⭐️</span></h2>
                <p class="mb-2"><%= bookmark.movie.overview %></p>
                <p class="fs-6">‟<%= bookmark.comment %>”</p>
              </div>
              <%= link_to "delete", bookmark_path(bookmark), class: 'text-danger text-decoration-none fs-6', data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>